version: '3.8'

services:
  web:
    image: docker push rookblack/ocr_donor:web
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - app-data:/app/img

  worker:
    image: docker push rookblack/ocr_donor:worker
    depends_on:
      - redis
    volumes:
      - app-data:/app/img
      
  redis:
    image: docker push rookblack/ocr_donor:redis

volumes:
  app-data:
