version: '3.8'

services:
  web:
    image: darveivoldavara/ocr_for_medical_certificates:web
    ports:
      - "8000:8000"
    depends_on:
      - redis
  worker:
    image: darveivoldavara/ocr_for_medical_certificates:worker
    depends_on:
      - redis
  redis:
    image: darveivoldavara/ocr_for_medical_certificates:redis
